# will use the github actions to manage the infra on the cloud


name: ' Infra Configuring using Terraform on AWS' 

# no triggers only manual push
on: 
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Terraform Action'
        # input will be parameterized from drop down menu
        # like using script and input parameters in the Jenkins
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'plan'

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
permissions:
    # contents: read
    contents: write


jobs:
  infrastructure-setup-using-terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-24.04
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setting Up the Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"
          terraform_wrapper: true
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # cache to help us optimizing the runner times on different pushes
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
          
      - name: Initialising the Terraform
        run: terraform init

      - name: Terraform Format Check
        id : fmtcheck
        continue-on-error: true
      # use the -check to fail the pipeline on any issue an d shows the error line in the log
        run: terraform fmt -check -recursive --diff

      - name: Auto Fix Formatting
        if: steps.fmtcheck.outcome == 'failure'
        run: |
          echo "Formatting issues found â€” applying recursive fix"
          terraform fmt -recursive
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "*.tf"
          git add "*.tfvars" || true
          # Commit only if there are changes
          if ! git diff --cached --quiet; then
          # sync with the remote
            git fetch origin main
            git reset --soft origin/main
            git commit -m "Auto-format Terraform files (CI)"
            git push
          else
            echo "No formatting changes to commit."
          fi

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          set +e
          # log input file was missing
          terraform plan -input=false | tee -a results.log
          #QUOTES MISSING ""
          echo "TERRAFORM_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Set Terraform Plan Output
        if: ${{ github.event.inputs.action == 'plan' }}
        id: terraform-output-plan
        run: |
          {
            echo "log<<EOF"
            cat results.log
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          set +e
          terraform apply -auto-approve | tee -a results.log
          echo "TERRAFORM_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Set Terraform Apply Output
        if: ${{ github.event.inputs.action == 'apply' }}
        id: terraform-output-apply
        run: |
          {
            echo "log<<EOF"
            cat results.log
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Terraform destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          {
            echo "log<<EOF"
            cat results.log
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Set Terraform Destroy Output
        if: ${{ github.event.inputs.action == 'destroy' }}
        id: terraform-output-destroy
        run: |
          echo log<<EOF >> $GITHUB_OUTPUT
          cat results.log >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT


      - name: Send Terraform results by Email
      # always run even if previous steps fail
        if: always()  
        uses: dawidd6/action-send-mail@v3
        with:
          # sender creds
          # make it generic as user provides his creds in secerts
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: "Terraform Workflow Results - ${{ github.workflow }}"
          body: |
            Hello,

            Terraform workflow ${{ github.workflow }} has completed.

            Workflow run: ${{ github.run_number }}
            Repository: ${{ github.repository }}
            Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Exit code: ${{ env.TERRAFORM_EXIT_CODE }}

            Output log:
            ---------------------------------------------
            ${{ steps.terraform_output_plan.outputs.log }}
            ${{ steps.terraform_output_apply.outputs.log }}
            ${{ steps.terraform_output_destroy.outputs.log }}
            ---------------------------------------------

          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
